---
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /volume3/docker/freshrss/config:/config
    ports:
      - 80:80
    restart: unless-stopped
